# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arekibo - Jekyll boilerplate
email: brendan.macdonagh@arekibo.com
description: >- # this means to ignore newlines until "baseurl:"
  First Jekyll template
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

# social links 
social_links:
  - fontawesome_code : 'fa-facebook-f'
    url   : '#'
  - fontawesome_code : 'fa-youtube'
    url   : '#'
  - fontawesome_code : 'fa-twitter'
    url   : '#'
  - fontawesome_code : 'fa-instagram'
    url   : '#'
  - fontawesome_code : 'fa-linkedin-in'
    url   : '#'   

# Build settings

# removed as not using Jekyll to process Sass anymore
# sass:
  #   sass_dir: _sass


include: ['_pages']
markdown: redcarpet
kramdown:
  input: GFM         

exclude: ["vendor",
          "_assets",
          "Gemfile",
          "Gemfile.lock",
          "gulpfile.js",
          "node_modules",
          "package.json"]

picture:
  source: "assets/images/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    gallery:
      ppi: [1, 1.5]
      attr:
        class: "gallery-pict"
        itemprop: "image"
      source_medium:
        media: "(min-width: 40em)"
        width: "600"
        height: "300"
      source_default: 
        width: "300"
